### ISSUE TITLE
Links in docs/README.md are broken

### ISSUE THREAD

**Issue by jplatte** [matrix-org/matrix-authentication-service#1078]
What the title says.

**Comment by sandhose** [comment]
Right. This file is used in the mdBook published here, where thee links aren't broken: https://matrix-org.github.io/matrix-authentication-service/

I guess we could make those links absolute instead?

**Comment by jplatte** [comment]
Sounds like a good idea.

**Comment by sandhose** [comment]
This actually has been fixed for quite a while, closing

**Comment by jplatte** [comment]
I can still reproduce the problem, clicking on one of the last two links at https://github.com/matrix-org/matrix-authentication-service/tree/main/docs.

**Comment by sandhose** [comment]
Crap, you're right, I wasn't reading the URLs properly :D
